//
//  getMaxStringCount.swift
//  TryComponents
//
//  Created by オナガ・ハルキ on 2022/10/16.
//

import SwiftUI

struct getMaxStringCount: View {
    var char: String
    var body: some View {
        Text(char)
            .lineLimit(1)
            .font(.system(size: 50))
            .foregroundColor(.red)
            .background(.clear)
    }
}

struct getMaxStringCount_Previews: PreviewProvider {
    static var previews: some View {
//        getMaxStringCount(char: "a")
//        getMaxStringCount(char: "b")
//        getMaxStringCount(char: "c")
//        getMaxStringCount(char: "d")
//        getMaxStringCount(char: "e")
//        getMaxStringCount(char: "f")
//        getMaxStringCount(char: "g")
//        getMaxStringCount(char: "h")
//        getMaxStringCount(char: "i")
//        getMaxStringCount(char: "j")
//        getMaxStringCount(char: "k")
//        getMaxStringCount(char: "l")
//        getMaxStringCount(char: "m")
//        getMaxStringCount(char: "n")
//        getMaxStringCount(char: "o")
//        getMaxStringCount(char: "p")
//        getMaxStringCount(char: "q")
//        getMaxStringCount(char: "r")
//        getMaxStringCount(char: "s")
//        getMaxStringCount(char: "t")
//        getMaxStringCount(char: "u")
//        getMaxStringCount(char: "v")
//        getMaxStringCount(char: "w")
//        getMaxStringCount(char: "x")
//        getMaxStringCount(char: "y")
//        getMaxStringCount(char: "z")

//        getMaxStringCount(char: "A")
//        getMaxStringCount(char: "B")
//        getMaxStringCount(char: "C")
//        getMaxStringCount(char: "D")
//        getMaxStringCount(char: "E")
//        getMaxStringCount(char: "F")
//        getMaxStringCount(char: "G")
//        getMaxStringCount(char: "H")
//        getMaxStringCount(char: "I")
//        getMaxStringCount(char: "J")
//        getMaxStringCount(char: "K")
//        getMaxStringCount(char: "L")
//        getMaxStringCount(char: "M")
//        getMaxStringCount(char: "N")
//        getMaxStringCount(char: "O")
//        getMaxStringCount(char: "P")
//        getMaxStringCount(char: "Q")
//        getMaxStringCount(char: "R")
//        getMaxStringCount(char: "S")
//        getMaxStringCount(char: "T")
//        getMaxStringCount(char: "U")
//        getMaxStringCount(char: "V")
//        getMaxStringCount(char: "W")
//        getMaxStringCount(char: "X")
//        getMaxStringCount(char: "Y")
//        getMaxStringCount(char: "Z")
        
//        getMaxStringCount(char: "1")
//        getMaxStringCount(char: "2")
//        getMaxStringCount(char: "3")
//        getMaxStringCount(char: "4")
//        getMaxStringCount(char: "5")
//        getMaxStringCount(char: "6")
//        getMaxStringCount(char: "7")
//        getMaxStringCount(char: "8")
//        getMaxStringCount(char: "9")
//        getMaxStringCount(char: "0")
//        getMaxStringCount(char: "!")
//        getMaxStringCount(char: "@")
//        getMaxStringCount(char: "#")
//        getMaxStringCount(char: "$")
//        getMaxStringCount(char: "%")
//        getMaxStringCount(char: "^")
//        getMaxStringCount(char: "&")
//        getMaxStringCount(char: "*")
//        getMaxStringCount(char: "(")
//        getMaxStringCount(char: ")")
//        getMaxStringCount(char: "-")
//        getMaxStringCount(char: "_")
//        getMaxStringCount(char: "=")
//        getMaxStringCount(char: "+")
//        getMaxStringCount(char: "|")
//        getMaxStringCount(char: "`")
//        getMaxStringCount(char: "~")
//        getMaxStringCount(char: "[")
//        getMaxStringCount(char: "{")
//        getMaxStringCount(char: "]")
//        getMaxStringCount(char: "}")
//        getMaxStringCount(char: ";")
//        getMaxStringCount(char: ":")
//        getMaxStringCount(char: "'")
//        getMaxStringCount(char: ",")
//        getMaxStringCount(char: ".")
//        getMaxStringCount(char: "<")
//        getMaxStringCount(char: ">")
//        getMaxStringCount(char: "/")
        getMaxStringCount(char: "?")
    }
}
